todolist_list_homepage:
    pattern:  /TODOList
    defaults: { _controller: TODOListBundle:Default:index }

todolist_list_tasklists:
    pattern:  /TODOList/lists
    defaults: { _controller: TODOListBundle:TaskLists:getTaskLists }

todolist_new_tasklists:
    pattern:  /TODOList/lists/new
    defaults: { _controller: TODOListBundle:TaskLists:newTaskList }

todolist_delete_tasklists:
    pattern: /TODOList/lists/delete
    defaults: { _controller: TODOListBundle:TaskLists:deleteTaskList }

todolist_update_tasklists:
    pattern: /TODOList/lists/update/{idTaskList}
    defaults: { _controller: TODOListBundle:TaskLists:updateTaskList }
    requirements:
      idTaskList: \d+

todolist_list_tasks:
    pattern:  /TODOList/lists/{idTaskList}/tasks
    defaults: { _controller: TODOListBundle:Tasks:getTasks }
    requirements:
        idTaskList: \d+

todolist_new_tasks:
    pattern:  /TODOList/lists/{idTaskList}/tasks/new
    defaults: { _controller: TODOListBundle:Tasks:newTask }
    requirements:
        idTaskList: \d+

todolist_delete_tasks:
    pattern: /TODOList/lists/{idTaskList}/tasks/delete
    defaults: { _controller: TODOListBundle:TaskLists:deleteTask }
    requirements:
      idTaskList: \d+

todolist_update_tasks:
    pattern: /TODOList/lists/{idTaskList}/tasks/update/{idTask}
    defaults: { _controller: TODOListBundle:TaskLists:updateTask }
    requirements:
      idTaskList: \d+
      idTask: \d+