todolist_homepage:
    path:  /
    defaults: { _controller: TODOListBundle:TaskLists:index }

todolist_list_homepage:
    path:  /TODOList
    defaults: { _controller: TODOListBundle:TaskLists:index }

# LOCAL STORAGE #
todolist_list_tasklists:
    path:  /TODOList/lists
    defaults: { _controller: TODOListBundle:TaskLists:getTaskLists }

todolist_new_tasklists:
    path:  /TODOList/lists/new
    defaults: { _controller: TODOListBundle:TaskLists:newTaskList }

todolist_delete_tasklists:
    path: /TODOList/lists/delete
    defaults: { _controller: TODOListBundle:TaskLists:deleteTaskList }

todolist_update_tasklists:
    path: /TODOList/lists/update/{idTaskList}
    defaults: { _controller: TODOListBundle:TaskLists:updateTaskList }

todolist_list_tasks:
    path:  /TODOList/lists/{idTaskList}/tasks
    defaults: { _controller: TODOListBundle:Tasks:getTasks }

todolist_new_tasks:
    path:  /TODOList/lists/{idTaskList}/tasks/new
    defaults: { _controller: TODOListBundle:Tasks:newTask }

todolist_delete_tasks:
    path: /TODOList/lists/{idTaskList}/tasks/delete
    defaults: { _controller: TODOListBundle:Tasks:deleteTask }
    requirements:
      idTaskList: \d+

todolist_update_tasks:
    path: /TODOList/lists/{idTaskList}/tasks/update/{idTask}
    defaults: { _controller: TODOListBundle:Tasks:updateTask }
    requirements:
      idTaskList: \d+
      idTask: \d+

todolist_status_tasks:
    path: /TODOList/lists/{idTaskList}/tasks/status/{idTask}
    defaults: { _controller: TODOListBundle:Tasks:statusTask }

# Google Api #
todolist_oauth_callback:
    path: /TODOList/oauth/callback
    defaults: { _controller: TODOListBundle:OAuth:callback }

todolist_oauth_exit:
    path: /TODOList/oauth/exit
    defaults: { _controller: TODOListBundle:OAuth:exit }

todolist_googleapi_list_taskslists:
    path: /TODOList/googleapi/lists
    defaults: { _controller: TODOListBundle:TaskListsGoogleApi:getTaskLists }

todolist_googleapi_new_tasklists:
    path:  /TODOList/googleapi/lists/new
    defaults: { _controller: TODOListBundle:TaskListsGoogleApi:newTaskList }

todolist_googleapi_delete_tasklists:
    path: /TODOList/googleapi/lists/delete
    defaults: { _controller: TODOListBundle:TaskListsGoogleApi:deleteTaskList }

todolist_googleapi_update_tasklists:
    path: /TODOList/googleapi/lists/update/{idTaskList}
    defaults: { _controller: TODOListBundle:TaskListsGoogleApi:updateTaskList }

todolist_googleapi_list_tasks:
    path:  /TODOList/googleapi/lists/{idTaskList}/tasks
    defaults: { _controller: TODOListBundle:TasksGoogleApi:getTasks }

todolist_googleapi_new_tasks:
    path:  /TODOList/googleapi/lists/{idTaskList}/tasks/new
    defaults: { _controller: TODOListBundle:TasksGoogleApi:newTask }

todolist_googleapi_delete_tasks:
    path: /TODOList/googleapi/lists/{idTaskList}/tasks/delete
    defaults: { _controller: TODOListBundle:TasksGoogleApi:deleteTask }

todolist_googleapi_update_tasks:
    path: /TODOList/googleapi/lists/{idTaskList}/tasks/update/{idTask}
    defaults: { _controller: TODOListBundle:TasksGoogleApi:updateTask }

todolist_googleapi_status_tasks:
    path: /TODOList/googleapi/lists/{idTaskList}/tasks/status/{idTask}
    defaults: { _controller: TODOListBundle:TasksGoogleApi:statusTask }
