parameters:
#    todo_list.example.class: Acme\TODOListBundle\Example

services:
#    todo_list.example:
#        class: %todo_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
